# Generated by Django 2.1.2 on 2019-05-13 13:24

import datetime
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Hero',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=32, null=True)),
                ('race', models.CharField(choices=[('human', 'Human'), ('dwarf', 'Dwarf'), ('elf', 'Elf'), ('halfling', 'Halfling')], default='Human', max_length=16)),
                ('current_career', models.CharField(choices=[('agitator', 'Agitator'), ('apprentice_wizard', 'Apprentice Wizard'), ('bailiff', 'Bailiff'), ('barber-surgeon', 'Barber-Surgeon'), ('boatman', 'Boatman'), ('bodyguard', 'Bodyguard'), ('bone_picker', 'Bone Picker'), ('bounty_hunter', 'Bounty Hunter'), ('burgher', 'Burgher'), ('camp_follower', 'Camp Follower'), ('charcoal-burner', 'Charcoal-Burner'), ('coachman', 'Coachman'), ('entertainer', 'Entertainer'), ('envoy', 'Envoy'), ('estalian_diestro', 'Estalian Diestro'), ('ferryman', 'Ferryman'), ('fieldwarden', 'Fieldwarden'), ('fisherman', 'Fisherman'), ('grave_robber', 'Grave Robber'), ('hedge_wizard', 'Hedge Wizard'), ('hunter', 'Hunter'), ('initiate', 'Initiate'), ('jailer', 'Jailer'), ('kislevite_kossar', 'Kislevite Kossar'), ('kithband_warrior', 'Kithband Warrior'), ('marine', 'Marine'), ('mercenary', 'Mercenary'), ('messenger', 'Messenger'), ('militiaman', 'Militiaman'), ('miner', 'Miner'), ('noble', 'Noble'), ('norse_berserker', 'Norse Berserker'), ('outlaw', 'Outlaw'), ('outrider', 'Outrider'), ('peasant', 'Peasant'), ('pit_fighter', 'Pit Fighter'), ('protagonist', 'Protagonist'), ('rat_catcher', 'Rat Catcher'), ('roadwarden', 'Roadwarden'), ('rogue', 'Rogue'), ('runebearer', 'Runebearer'), ('scribe', 'Scribe'), ('seaman', 'Seaman'), ('servant', 'Servant'), ('shieldbreaker', 'Shieldbreaker'), ('smuggler', 'Smuggler'), ('soldier', 'Soldier'), ('squire', 'Squire'), ('student', 'Student'), ('thief', 'Thief'), ('thug', 'Thug'), ('toll_keeper', 'Toll Keeper'), ('tomb_robber', 'Tomb Robber'), ('tradesman', 'Tradesman'), ('troll_slayer', 'Troll Slayer'), ('vagabond', 'Vagabond'), ('valet', 'Valet'), ('watchman', 'Watchman'), ('woodsman', 'Woodsman'), ('zealot', 'Zealot')], default='Mercenary', max_length=32)),
                ('previous_careers', models.CharField(blank=True, max_length=32, null=True)),
                ('age', models.SmallIntegerField(blank=True, null=True)),
                ('gender', models.CharField(choices=[('male', 'Male'), ('female', 'Female')], default='Male', max_length=16)),
                ('eye_color', models.CharField(blank=True, max_length=16, null=True)),
                ('hair_color', models.CharField(blank=True, max_length=16, null=True)),
                ('weight', models.SmallIntegerField(blank=True, null=True)),
                ('height', models.SmallIntegerField(blank=True, null=True)),
                ('star_sign', models.CharField(blank=True, max_length=32, null=True)),
                ('number_of_siblings', models.SmallIntegerField(blank=True, null=True)),
                ('birthplace', models.CharField(blank=True, max_length=32, null=True)),
                ('distinguishing_marks', models.CharField(blank=True, max_length=32, null=True)),
                ('weapon_skill', models.SmallIntegerField(default=20, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('ballistic_skill', models.SmallIntegerField(default=20, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('strength', models.SmallIntegerField(default=20, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('toughness', models.SmallIntegerField(default=20, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('agility', models.SmallIntegerField(default=20, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('intelligence', models.SmallIntegerField(default=20, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('will_power', models.SmallIntegerField(default=20, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('fellowship', models.SmallIntegerField(default=20, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('attacks', models.SmallIntegerField(default=1, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(20)])),
                ('wounds', models.SmallIntegerField(default=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('strength_bonus', models.SmallIntegerField(default=1, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(20)])),
                ('toughness_bonus', models.SmallIntegerField(default=1, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(20)])),
                ('movement', models.SmallIntegerField(default=1, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(20)])),
                ('magic', models.SmallIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(20)])),
                ('insanity_points', models.SmallIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)])),
                ('fate_points', models.SmallIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)])),
                ('experience', models.SmallIntegerField(default=0)),
                ('portrait', models.SmallIntegerField(blank=True, null=True, verbose_name=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(8)])),
                ('game_master', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='game_master', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='player', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='News', max_length=32)),
                ('content', models.TextField(null=True)),
                ('date_added', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('category', models.CharField(blank=True, max_length=32, null=True)),
                ('picture', models.ImageField(blank=True, default='news/default.jpg', null=True, upload_to='news/%Y/%m/%d')),
                ('added_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='added_by', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
