# Generated by Django 2.2.1 on 2019-05-26 12:24

from django.db import migrations, models
import rpg_hero_creator.warhammer_hero_creator.models


class Migration(migrations.Migration):

    dependencies = [
        ('warhammer_hero_creator', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hero',
            name='portrait',
            field=models.ImageField(blank=True, default='portraits/default.jpg', null=True, upload_to=rpg_hero_creator.warhammer_hero_creator.models.portrait_path),
        ),
    ]
